### ISSUE TITLE
Create colour scheme

### ISSUE THREAD

**Issue by CameronMcDougall** [CameronMcDougall/ShapeGameProject#10]
The levels require better colour scheming for objects. Terrain should look different than puzzle terrain (platforms, ramps), which should look different than interactable objects (buttons).
- [ ] Colour for terrain
- [ ] Colour for puzzle terrain
- [ ] Colour for buttons
- [ ] Colour for water objects
- [ ] Make materials in Unity which are appropriately named (i.e. Terrain)

**Comment by quanle0711** [comment]
Done, finished by benSpearman1
