### ISSUE TITLE
Playtesting feedback - welsfofinn - Finn Welsford-Ackroyd

### ISSUE THREAD

**Issue by quanle0711** [CameronMcDougall/ShapeGameProject#18]
I got stuck on the third level, as I couldn't see the pattern in the movement of the objects. It felt a bit chaotic and as if I had to resort to trial and error. I tried sitting on the moving object I could access and then jumping across to the ones that crossed its path. I managed around eight or so attempts before deforming but didn't feel like I made much progress.

**Comment by CameronMcDougall** [comment]
The main problem was that the speed of movement of the tubes was too fast, making it harder for the user to think about the problem and see the path pattern. Animations were also buggy as tubes would collide with each other making the players movement more difficult.

Ben has fixed this issue by fixing the animations and making the speed of the movement of the tubes slower.
