### ISSUE TITLE
Tube modular models

### ISSUE THREAD

**Issue by CameronMcDougall** [CameronMcDougall/ShapeGameProject#9]
- [x] Create Tube straight short
- [ ] Create tube straight med
- [ ] Create tube straight long
- [ ] Create tube left turn angle (make sure player can turn through it easily)
- [ ] Create tube right turn angle
- [ ] Create tube ramp straight short
- [ ] Create tube ramp straight med
- [ ] Create tube ramp straight long
- [ ] Create tube spiral (1 story tall)

**Comment by BenJSpearman** [comment]
No longer needed, level designs have changed
